version: '3.2'

# use this to startup the NewsLookout web scraper

services:

  newslookout_web_scraper:

    image: newslookout:2.1.0

    container_name: newslookout

    environment:
      - NLTK_DATA="/opt/models/nltk"
      - "TZ=Asia/Kolkata"

    volumes:
      # - host_config:/etc/newslookout:rw
      - host_dataset:/var/cache/newslookout_data:rw
      - host_models:/opt/models:rw
      - host_logs:/var/log/newslookout:rw

    # networks:
      # - newslookout_network

    ports:
      - '22:1022'

networks:
  # The presence of these objects is sufficient to define them
  newslookout_network: {}

volumes:

  host_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\shared\newslookout\conf

  host_dataset:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: c:\shared\newslookout\web_scraped_data

  host_models:
    # for storing the BERT and other NLP model files.
    driver: local
    driver_opts:
      type: none
      o: bind
      device: c:\shared\newslookout\models

  host_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: c:\shared\newslookout\logs
